// The secrets manifest that ships inside every archive — names, never values.
//
// `secrets/` is always excluded from a backup (D1), so a restored machine has
// every file it needs and none of the credentials. This manifest is the list
// of what is missing, built from the REAL vault via `SecretsResolver.list()`.
//
// The manifest `apps/ethos/src/commands/backup.ts` writes today reads
// `keys.json` instead, which is only the LLM key-rotation pool: a machine
// whose credentials all live in `~/.ethos/secrets/` gets an empty list and no
// warning. Every vault ref is enumerated here, grouped the way it is namespaced
// (`<key>`, `personalities/<id>/<key>`, and anything else verbatim).
//
// The one thing that never appears: a value. `list()` returns refs; `get()` is
// never called.

import { PersonalityScopedSecrets } from '@ethosagent/storage-fs';
import type { SecretsResolver } from '@ethosagent/types';

/** Archive-relative path of the manifest entry. */
export const SECRETS_MANIFEST_PATH = 'secrets.manifest.yaml';

const PERSONALITY_PREFIX = 'personalities/';

export interface SecretsManifestInit {
  /** The vault to enumerate. Only `list()` is called. */
  secrets: SecretsResolver;
  /** personality id → MCP server dirs whose OAuth tokens were stripped. */
  strippedMcpTokens: Map<string, Set<string>>;
  /** Overridable for deterministic tests. */
  now?: Date;
}

interface PersonalityEntry {
  /** Vault keys, relative to the personality's namespace. */
  secrets: string[];
  /** MCP servers whose token files were left out of the archive. */
  mcpServers: string[];
}

/**
 * Render the manifest. Refs are sorted so two backups of an unchanged vault
 * produce a byte-identical manifest apart from `backed_up_at`.
 */
export async function buildSecretsManifest(init: SecretsManifestInit): Promise<string> {
  const refs = (await init.secrets.list()).slice().sort();

  const global: string[] = [];
  const other: string[] = [];
  const personalities = new Map<string, PersonalityEntry>();

  const entryFor = (id: string): PersonalityEntry => {
    let entry = personalities.get(id);
    if (!entry) {
      entry = { secrets: [], mcpServers: [] };
      personalities.set(id, entry);
    }
    return entry;
  };

  for (const ref of refs) {
    if (!ref.includes('/')) {
      global.push(ref);
      continue;
    }
    if (ref.startsWith(PERSONALITY_PREFIX)) {
      const rest = ref.slice(PERSONALITY_PREFIX.length);
      const slash = rest.indexOf('/');
      if (slash > 0) {
        entryFor(rest.slice(0, slash)).secrets.push(rest.slice(slash + 1));
        continue;
      }
    }
    other.push(ref);
  }

  for (const [id, servers] of init.strippedMcpTokens) {
    entryFor(id).mcpServers.push(...servers);
  }

  const lines: string[] = [
    '# Generated by ethos backup — re-enter these secrets after restoring.',
    '# Names only: no secret value is ever written to an archive.',
    `backed_up_at: ${(init.now ?? new Date()).toISOString()}`,
  ];

  if (global.length > 0) {
    lines.push('', 'global:');
    for (const key of global) {
      lines.push(`  - key: ${key}`, `    fill_with: ethos secrets set ${key} <value>`);
    }
  }

  const ids = [...personalities.keys()].sort();
  if (ids.length > 0) {
    lines.push('', 'personalities:');
    for (const id of ids) {
      const entry = personalities.get(id);
      if (!entry) continue;
      lines.push(`  ${id}:`);
      if (entry.secrets.length > 0) {
        lines.push('    secrets:');
        for (const key of entry.secrets.slice().sort()) {
          const ref = `${PERSONALITY_PREFIX}${id}/${key}`;
          lines.push(`      - key: ${key}`, `        fill_with: ethos secrets set ${ref} <value>`);
        }
      }
      if (entry.mcpServers.length > 0) {
        lines.push('    mcp_auth:');
        for (const server of [...new Set(entry.mcpServers)].sort()) {
          lines.push(`      - server: ${server}`, `        fill_with: ethos mcp auth ${server}`);
        }
      }
    }
  }

  if (other.length > 0) {
    lines.push('', 'other:');
    for (const ref of other) {
      lines.push(`  - key: ${ref}`, `    fill_with: ethos secrets set ${ref} <value>`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Injection — the operator-written manifest that carries values
// ---------------------------------------------------------------------------
//
// A separate, simpler format from the one above, unchanged from the CLI's
// implementation so existing manifests keep working:
//
//   global:
//     KEY: value
//   personalities:
//     <id>:
//       KEY: value
//
// Values are trimmed; a matching pair of quotes is stripped. `#` comments and
// blank lines are ignored. An EMPTY value is skipped rather than written — a
// half-filled template must not overwrite a good secret with ''.

interface ParsedSecrets {
  global: Map<string, string>;
  personalities: Map<string, Map<string, string>>;
}

function stripQuotes(s: string): string {
  if (s.length >= 2 && ((s[0] === '"' && s.at(-1) === '"') || (s[0] === "'" && s.at(-1) === "'"))) {
    return s.slice(1, -1);
  }
  return s;
}

function parseSecretsManifest(raw: string): ParsedSecrets {
  const global = new Map<string, string>();
  const personalities = new Map<string, Map<string, string>>();

  let section: 'none' | 'global' | 'personalities' = 'none';
  let currentPersonality: string | undefined;

  for (const line of raw.split('\n')) {
    const trimmed = line.trimEnd();
    if (!trimmed || trimmed.trimStart().startsWith('#')) continue;

    const indent = line.length - line.trimStart().length;

    if (indent === 0 && trimmed.endsWith(':')) {
      const header = trimmed.slice(0, -1);
      if (header === 'global') {
        section = 'global';
        currentPersonality = undefined;
      } else if (header === 'personalities') {
        section = 'personalities';
        currentPersonality = undefined;
      } else {
        section = 'none';
        currentPersonality = undefined;
      }
      continue;
    }

    if (section === 'personalities' && indent === 2 && trimmed.endsWith(':')) {
      currentPersonality = trimmed.slice(0, -1).trim();
      if (!personalities.has(currentPersonality)) personalities.set(currentPersonality, new Map());
      continue;
    }

    const colonIdx = trimmed.indexOf(':');
    if (colonIdx < 0) continue;
    const key = trimmed.slice(0, colonIdx).trim();
    const value = stripQuotes(trimmed.slice(colonIdx + 1).trim());
    if (!key || !value) continue;

    if (section === 'global' && indent >= 2) {
      global.set(key, value);
    } else if (section === 'personalities' && indent >= 4 && currentPersonality) {
      const pMap = personalities.get(currentPersonality);
      if (pMap) pMap.set(key, value);
    }
  }

  return { global, personalities };
}

/**
 * Write every value in `raw` into `secrets`. Returns how many were written.
 * Personality-scoped keys land under `personalities/<id>/` via the same
 * wrapper the rest of the system writes them with.
 */
export async function injectSecrets(raw: string, secrets: SecretsResolver): Promise<number> {
  const parsed = parseSecretsManifest(raw);
  let count = 0;

  for (const [key, value] of parsed.global) {
    await secrets.set(key, value);
    count++;
  }
  for (const [id, kvs] of parsed.personalities) {
    const scoped = new PersonalityScopedSecrets(secrets, id);
    for (const [key, value] of kvs) {
      await scoped.set(key, value);
      count++;
    }
  }
  return count;
}
