import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { promisify } from 'node:util';
import { type VoiceAudioFormat, voiceAudioMimeType } from '@ethosagent/types';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createFfmpegTranscoder } from '../transcode';

// ---------------------------------------------------------------------------
// The ONLY coverage of the real ffmpeg arg strings in `ENCODER_ARGS`.
//
// `transcode.test.ts` drives the injected `run` seam, so it proves the stage's
// control flow (fallback, timeout, pass-through, cleanup) without ever
// executing ffmpeg. That leaves the arg strings themselves — `-c:a libopus`,
// `-f ipod`, `-f adts` — validated by nothing: a typo in a codec name or a
// container flag typechecks, passes the seam tests, and fails for the first
// time on a user's machine, at the moment they send a voice note.
//
// This suite runs the real binary and inspects the real bytes. It is opt-in by
// ENVIRONMENT rather than by mock: ffmpeg is an external dependency the repo
// does not vendor, so a host without it reports SKIPPED (never failed) via the
// probe below. On a host that has ffmpeg — the kind that actually ships voice —
// it runs, and the arg table is covered.
//
// Fixtures are generated by ffmpeg itself, so no binary audio enters the repo.
// ---------------------------------------------------------------------------

const exec = promisify(execFile);

/** ffmpeg is fast on a 2s tone, but CI hosts vary — be generous. */
const TIMEOUT_MS = 30_000;

/** `-f lavfi -i sine=...` parameters, and what they imply for the raw pcm size. */
const TONE_SECONDS = 2;
const TONE_SAMPLE_RATE = 16_000;
/** 16-bit mono at 16kHz for `TONE_SECONDS`. `pcm` output must be exactly this. */
const EXPECTED_PCM_BYTES = TONE_SECONDS * TONE_SAMPLE_RATE * 2;

const transcoder = createFfmpegTranscoder({});
// Probed at collection time, not in `beforeAll`: `describe.skipIf` needs the
// answer before the suite is registered, and a hook result arrives too late to
// turn these tests into skips rather than failures.
const hasFfmpeg = await transcoder.available();

/** Scratch root for this file — see the `beforeAll` note on TMPDIR. */
let tempRoot: string;
let probeSeq = 0;

function ascii(data: Uint8Array, start: number, length: number): string {
  return Buffer.from(data.subarray(start, start + length)).toString('latin1');
}

function hex(data: Uint8Array, start: number, length: number): string {
  return Buffer.from(data.subarray(start, start + length)).toString('hex');
}

/** ffprobe's view of the first audio stream's codec. */
async function probeCodec(data: Uint8Array, extension: string): Promise<string> {
  const path = join(tempRoot, `probe-${probeSeq++}.${extension}`);
  await writeFile(path, data);
  const { stdout } = await exec('ffprobe', [
    '-v',
    'error',
    '-select_streams',
    'a:0',
    '-show_entries',
    'stream=codec_name',
    '-of',
    'default=nw=1:nk=1',
    path,
  ]);
  return stdout.trim();
}

/**
 * One assertion per target format: is this REALLY that container, holding the
 * codec the arg string asked for? Magic bytes where they are conclusive,
 * ffprobe where they are not — the choice is noted per case.
 *
 * `wav` is absent on purpose: the fixture is wav, so a wav target is the
 * pass-through path and gets its own test. `silk` and `amr` cannot be produced
 * by a stock build and get their own tests too.
 */
const FORMAT_CASES: ReadonlyArray<{
  format: VoiceAudioFormat;
  verify: (data: Uint8Array) => Promise<void>;
}> = [
  {
    format: 'opus',
    // `OggS` proves the container. It does NOT prove the codec — a vorbis .ogg
    // opens identically — and `-c:a libopus` is half of what we are guarding,
    // so ffprobe answers that half.
    verify: async (data) => {
      expect(ascii(data, 0, 4)).toBe('OggS');
      expect(await probeCodec(data, 'ogg')).toBe('opus');
    },
  },
  {
    format: 'ogg',
    // Same container, and the arg table deliberately encodes opus into it too.
    verify: async (data) => {
      expect(ascii(data, 0, 4)).toBe('OggS');
      expect(await probeCodec(data, 'ogg')).toBe('opus');
    },
  },
  {
    format: 'mp3',
    // libmp3lame writes an ID3v2 header; a bare stream would open with an
    // 11-bit frame sync instead. Accept either, then let ffprobe confirm the
    // payload is mp3 rather than something wearing an ID3 tag.
    verify: async (data) => {
      const frameSync = data[0] === 0xff && ((data[1] ?? 0) & 0xe0) === 0xe0;
      expect(ascii(data, 0, 3) === 'ID3' || frameSync).toBe(true);
      expect(await probeCodec(data, 'mp3')).toBe('mp3');
    },
  },
  {
    format: 'm4a',
    // ISO-BMFF puts `ftyp` at offset 4, after the box length. The brand says
    // nothing about the audio codec (alac lives in .m4a too), so ffprobe again.
    verify: async (data) => {
      expect(ascii(data, 4, 4)).toBe('ftyp');
      expect(await probeCodec(data, 'm4a')).toBe('aac');
    },
  },
  {
    format: 'aac',
    // A raw ADTS sync word (0xFFF1 / 0xFFF9) is conclusive on its own — it is
    // the container and an AAC-only marker at once. No ffprobe needed.
    verify: async (data) => {
      expect(['fff1', 'fff9']).toContain(hex(data, 0, 2));
    },
  },
  {
    format: 'flac',
    // `fLaC` is codec and container at once — conclusive.
    verify: async (data) => {
      expect(ascii(data, 0, 4)).toBe('fLaC');
    },
  },
  {
    format: 'webm',
    // The EBML magic is shared by every matroska/webm file and says nothing
    // about the audio track, so ffprobe checks that `-c:a libopus` landed.
    verify: async (data) => {
      expect(hex(data, 0, 4)).toBe('1a45dfa3');
      expect(await probeCodec(data, 'webm')).toBe('opus');
    },
  },
  {
    format: 'pcm',
    // Raw samples: there are no magic bytes to check. The honest assertion is
    // the arithmetic — `-ac 1 -ar 16000` at 16 bits has exactly one size.
    verify: async (data) => {
      expect(data.length).toBe(EXPECTED_PCM_BYTES);
    },
  },
];

describe.skipIf(!hasFfmpeg)('createFfmpegTranscoder — real ffmpeg', () => {
  let sourceWav: Uint8Array;

  beforeAll(async () => {
    // The module writes its scratch to `os.tmpdir()` under a shared
    // `ethos-transcode-` prefix, and transcode.test.ts asserts that no file
    // with that prefix is left in `os.tmpdir()`. A real ffmpeg run holds those
    // files for tens of milliseconds — long enough to land inside that
    // snapshot if the two files run in parallel. Redirecting TMPDIR (safe:
    // vitest gives each test file its own process) keeps this suite's scratch
    // out of the shared directory entirely.
    tempRoot = await mkdtemp(join(tmpdir(), 'ethos-ffmpeg-itest-'));
    process.env.TMPDIR = tempRoot;

    const sourcePath = join(tempRoot, 'source.wav');
    await exec('ffmpeg', [
      '-hide_banner',
      '-loglevel',
      'error',
      '-y',
      '-f',
      'lavfi',
      '-i',
      `sine=frequency=440:duration=${TONE_SECONDS}`,
      '-ac',
      '1',
      '-ar',
      String(TONE_SAMPLE_RATE),
      sourcePath,
    ]);
    sourceWav = new Uint8Array(await readFile(sourcePath));
    expect(ascii(sourceWav, 0, 4)).toBe('RIFF');
  }, TIMEOUT_MS);

  afterAll(async () => {
    await rm(tempRoot, { recursive: true, force: true });
  });

  it.each(FORMAT_CASES)(
    'encodes a real $format file',
    async ({ format, verify }) => {
      const result = await transcoder.transcode({
        data: sourceWav,
        sourceMimeType: 'audio/wav',
        targets: [format],
      });

      if (!result.ok) throw new Error(`expected ${format} to encode, got: ${result.error}`);
      expect(result.format).toBe(format);
      expect(result.mimeType).toBe(voiceAudioMimeType(format));
      expect(result.transcoded).toBe(true);
      expect(result.fallbackFrom).toBeUndefined();
      expect(result.data.length).toBeGreaterThan(0);
      await verify(result.data);
    },
    TIMEOUT_MS,
  );

  it(
    'passes wav bytes through untouched when the source is already wav',
    async () => {
      const result = await transcoder.transcode({
        data: sourceWav,
        sourceMimeType: 'audio/wav',
        targets: ['wav'],
      });

      if (!result.ok) throw new Error(`expected pass-through, got: ${result.error}`);
      expect(result.transcoded).toBe(false);
      // The same reference, not merely equal bytes: proof ffmpeg never ran.
      expect(result.data).toBe(sourceWav);
      expect(result.mimeType).toBe(voiceAudioMimeType('wav'));
      expect(ascii(result.data, 8, 4)).toBe('WAVE');
    },
    TIMEOUT_MS,
  );

  it(
    'falls back to a real mp3 when the primary target is silk',
    async () => {
      const result = await transcoder.transcode({
        data: sourceWav,
        sourceMimeType: 'audio/wav',
        targets: ['silk', 'mp3'],
      });

      if (!result.ok) throw new Error(`expected the mp3 fallback to succeed, got: ${result.error}`);
      expect(result.format).toBe('mp3');
      expect(result.fallbackFrom).toBe('silk');
      expect(await probeCodec(result.data, 'mp3')).toBe('mp3');
    },
    TIMEOUT_MS,
  );

  it(
    'refuses silk instead of producing a mislabelled container',
    async () => {
      const result = await transcoder.transcode({
        data: sourceWav,
        sourceMimeType: 'audio/wav',
        targets: ['silk'],
      });

      if (result.ok) throw new Error('expected silk to fail on a stock ffmpeg');
      expect(result.code).toBe('failed');
      expect(result.error).toContain('silk requires a platform-specific encoder');
    },
    TIMEOUT_MS,
  );

  it(
    'either produces a real amr file or fails honestly',
    async () => {
      // amr is BUILD-DEPENDENT: `libopencore_amrnb` is an external library that
      // stock Homebrew and the common static builds omit, so this test cannot
      // demand either outcome without breaking on half the hosts. What it does
      // demand is that the outcome is HONEST — a real AMR container, or a typed
      // failure. Never bytes labelled audio/amr that no phone can play.
      //
      // Nothing depends on the success branch: no shipped adapter declares amr
      // as an OUTBOUND format (WhatsApp lists it inbound only), so a caps list
      // ending in amr degrades through the fallback walk rather than dying.
      const result = await transcoder.transcode({
        data: sourceWav,
        sourceMimeType: 'audio/wav',
        targets: ['amr'],
      });

      if (result.ok) {
        expect(ascii(result.data, 0, 6)).toBe('#!AMR\n');
        return;
      }
      expect(result.code).toBe('failed');
      expect(result.error.length).toBeGreaterThan(0);
    },
    TIMEOUT_MS,
  );
});
